In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
# Python Program illustrating 
# numpy.reshape() method 
  
import numpy as geek 
  
array = geek.arange(8) 
print("Original array : \n", array) 
  
# shape array with 2 rows and 4 columns 
array = geek.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# shape array with 4 rows and 2 columns 
array = geek.arange(8).reshape(4 ,2) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# Constructs 3D array 
array = geek.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : \n", array) 

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
import numpy as np


In [ ]:
df=pd.read_excel("/content/sales-funnel.xlsx")
df.head()

Account                          Name  ...  Price     Status
0   714466               Trantow-Barrows  ...  30000  presented
1   714466               Trantow-Barrows  ...  10000  presented
2   714466               Trantow-Barrows  ...   5000    pending
3   737550  Fritsch, Russel and Anderson  ...  35000   declined
4   146832                  Kiehn-Spinka  ...  65000        won

[5 rows x 8 columns]

In [ ]:
pd.pivot_table(df,index=["Rep"])

Account         Price  Quantity
Rep                                            
Cedric Moss    196016.5  27500.000000  1.250000
Craig Booker   720237.0  20000.000000  1.250000
Daniel Hilton  194874.0  38333.333333  1.666667
John Smith     576220.0  20000.000000  1.500000
Wendy Yule     614061.5  44250.000000  3.000000

In [ ]:
pd.pivot_table(df,index=["Name"])

Account   Price  Quantity
Name                                                   
Barton LLC                     740150   35000  1.000000
Fritsch, Russel and Anderson   737550   35000  1.000000
Herman LLC                     141962   65000  2.000000
Jerde-Hilpert                  412290    5000  2.000000
Kassulke, Ondricka and Metz    307599    7000  3.000000
Keeling LLC                    688981  100000  5.000000
Kiehn-Spinka                   146832   65000  2.000000
Koepp Ltd                      729833   35000  2.000000
Kulas Inc                      218895   25000  1.500000
Purdy-Kunde                    163416   30000  1.000000
Stokes LLC                     239344    7500  1.000000
Trantow-Barrows                714466   15000  1.333333

In [ ]:
pd.pivot_table(df,index=["Rep","Name","Manager"])

Account  ...  Quantity
Rep           Name                         Manager                 ...          
Cedric Moss   Herman LLC                   Fred Anderson   141962  ...  2.000000
              Purdy-Kunde                  Fred Anderson   163416  ...  1.000000
              Stokes LLC                   Fred Anderson   239344  ...  1.000000
Craig Booker  Fritsch, Russel and Anderson Debra Henley    737550  ...  1.000000
              Trantow-Barrows              Debra Henley    714466  ...  1.333333
Daniel Hilton Kiehn-Spinka                 Debra Henley    146832  ...  2.000000
              Kulas Inc                    Debra Henley    218895  ...  1.500000
John Smith    Barton LLC                   Debra Henley    740150  ...  1.000000
              Jerde-Hilpert                Debra Henley    412290  ...  2.000000
Wendy Yule    Kassulke, Ondricka and Metz  Fred Anderson   307599  ...  3.000000
              Keeling LLC                  Fred Anderson   688981  ...  5.000000
              Koepp Ltd                    Fred Anderson   729833  ...  2.000000

[12 rows x 3 columns]

In [ ]:
str1 = 'hello World!'
str2 = "Python Program"

In [ ]:
str1[0:6]

'Hello '

In [ ]:
str1.isupper()

False

In [ ]:
 str1.islower()

False

In [ ]:
str = "lets test the function";
print ("str.capitalize() : ", str.capitalize())

str.capitalize() :  Lets test the function


In [ ]:
str = "lets test the function";
print (str.islower())
str = "lets Test the function";
print (str.islower())

True
False
